### ISSUE TITLE
Recommended way to set report path?

### ISSUE THREAD

**Issue by fredrikaverpil** [realpython/pytest-mypy#108]
Hi, thanks for this excellent plugin! :heart:

We are running pytest like so; `pytest tests/unit_tests` and this generates a bunch of reports. Then we also run `pytest tests/component_tests`, which also generates a bunch of (different) reports. I use a `setup.cfg` file to configure both pytest and mypy.

Now, ideally, we want the mypy reports to be named accordingly ("unit" vs "component" respectively). Do you have a recommended approach on how to achieve this?
Right now, I've created a simple pytest plugin which analyses pytest's `config.args` and determines which type of test is executing and then it does the following:

```python
plugin = config.pluginmanager.getplugin("mypy")
plugin.mypy_argv.append(f"--html-report=reports/mypy/{test_type}")
```

But to me, this seems both hacky and a little excessive. There must be some easier way to achieve this?
Any ideas? 😃

**Comment by dmtucker** [comment]
That's the best way I'm aware of (and a pretty cool use-case IMO!)

I know it may seem like a little much, but it's the best balance I've found between requiring all config to be done in Mypy's config files and having to mirror all of `mypy`'s (unstable) CLI a la
https://github.com/dbader/pytest-mypy/blob/18fb2b81fa704d9cf9db1b82ce0e5ee32857a01a/src/pytest_mypy.py#L32-L34
Just to sanity-check, when you say that you have a simple plugin, are you referring to a `conftest.py`?
