### ISSUE TITLE
Pytest-mypy treats mypy annotation-unchecked warning as error

### ISSUE THREAD

**Issue by nidico** [realpython/pytest-mypy#145]
Since mypy 0.990, mypy emits a warning if a variable is annotated in a function without type annotation, see [mypy 0.990 release notes](https://mypy-lang.blogspot.com/2022/11/mypy-0990-released.html).

Such a warning ends up being reported as a test failure in pytest-mypy, erroneously.

**Comment by dmtucker** [comment]
Thanks for the report :slightly_smiling_face: I am able to reproduce it.
