### ISSUE TITLE
Option to suppress 'mypy-status' error

### ISSUE THREAD

**Issue by jaraco** [realpython/pytest-mypy#176]
When one of the mypy checks fail, it also reports a failure in the 'mypy-status' at the beginning of the test run. As a result, running with `-x` (fail fast) will always emit an inactionable error. Personally, I just find that error useless noise and I'd like to suppress it. Could you add an option to suppress this error and only report the per-file errors?

**Comment by dmtucker** [comment]
I didn't connect the two at first, but this sounds essentially the same as #120...
#179 delivers a suppression mechanism, `--mypy-no-status-check`, as-requested (which hadn't come up in that thread!),
but I'd like to improve the default behavior with `-x` at some point without having to suppress the status check too.
(FWIW, it's purpose is to indicate that `mypy` failed, which is the only indication anything went wrong when `mypy` on fails on one or more files that weren't collected by `pytest`.)
